version: "1"
services:

  front:
    image: react-app
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: sparta-backend
    depends_on:
      - db

    ports:
      - "8080:8080"
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"
      NO_PROXY: "${NO_PROXY}"
  db:
    image: postgres
    volumes:
      - sparta-db-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "komunist"
      POSTGRES_DB: postgres
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"
      NO_PROXY: "${NO_PROXY}"

    ports:
      - "5432:5432"
      - "5433:5432"

volumes:
  sparta-db-volume:
    external: true